### ISSUE TITLE
find treants of other packages.

### ISSUE THREAD

**Issue by kain88-de** [datreant/datreant.cli#3]
If I want to find other datreant specialized packages as well I would have to include them all at the beginning. Since I can't possibly know all of them this is a problem. One solution is to create a `~/.datreantrc`  which contains a list of specialized datreant packages. These would be loaded when `dtr` is started so that I can find the other Treants as well.

**Comment by dotsdl** [comment]
Should be solved by datreant/datreant.core#100, in which the conclusion was that we make everything a `Treant` in terms of its file usage and have no differing ``treanttype``s.

**Comment by kain88-de** [comment]
Solved upstream in datreant package
