### ISSUE TITLE
make installable

### ISSUE THREAD

**Issue by kain88-de** [datreant/datreant.cli#5]
The script is basically done. But right now I can't figure out how to write the setup.py correctly

@datreant/coredevs any idea?

**Comment by kain88-de** [comment]
@orbeckst Maybe you are interested in this too. I didn't do a lot of testing but it should allow to write bash code like this 
```bash
for folder in $(dtr search simulations --tags GB3 --categories gromacs:2016.4)
do
    # run some GROMACS functions or other things.
done
```

**Comment by richardjgowers** [comment]
@kain88-de if this is finished can we not just include it into the main package?

**Comment by kain88-de** [comment]
Nothing speaking against it but I'm not using click so this would mean adding another dependency. I see nothing against having this as a stand-alone package for some time and using it to see if we need to change it.

**Comment by orbeckst** [comment]
Does `datreant.cli` still thinks that datreant has namespace packages – is this the problem?

**Comment by kain88-de** [comment]
Nope it doesn't. We can also use a hyphen instead of the dot so name it `datreant-cli`. I'm not aware the dot is a problem but worth a check.

**Comment by dotsdl** [comment]
Unless something has changed in the python import system last time I researched it (>3 years ago), the dot would be a problem for importing the module. If you try to import `datreant.cli` and the import system finds the `datreant` package first, it won't find a `cli` module and would give on `ImportError`. A namespace package avoids this by being an umbrella in which nothing really lives but under which a bunch of modules are available.

See my comment in #4: let's make the CLI interface part of the `datreant` package itself.

**Comment by kain88-de** [comment]
yup replacing the dot with an underscore worked.

So this can be tested now. There will be bugs. I have not done any testing yet. I still have to update all of my projects to actually use the new datreant  version.

**Comment by kain88-de** [comment]
See https://github.com/datreant/datreant.cli/commit/7e1958683436d58ad0ba9774585460ec055d7132
